source 'https://github.com/CocoaPods/Specs.git'

target 'VOKMockUrlProtocol', :exclusive => true do
    pod "VOKMockUrlProtocol", :path => "../"
end

target 'Tests', :exclusive => true do
    pod "VOKMockUrlProtocol", :path => "../"
    pod "AFNetworking/Serialization"
end
