source 'https://github.com/CocoaPods/Specs.git'

target 'Tests' do
    pod "VOKMockUrlProtocol", :path => "../"
end

target 'Tests-tvOS' do
    platform :tvos, '9.0'
    pod "VOKMockUrlProtocol", :path => "../"
end

target 'Tests-OSX' do
    platform :osx, '10.9'
    pod "VOKMockUrlProtocol", :path => "../"
end
